### ISSUE TITLE
tests cases for josephus

### ISSUE THREAD

**Issue by calvinsettachatgul** [calvinsettachatgul/training#3]
https://github.com/calvinsettachatgul/training/blob/662ba74be54b9d45c3547cc89dc02b1daa8ac5a5/Josephus.java#L44

hi hugo what do you think about these tests cases? are the expected values correct?

**Comment by Hugosntss** [comment]
Yes, the expected values are correct and matching with mine results.

**Comment by calvinsettachatgul** [comment]
Oh great

**Comment by calvinsettachatgul** [comment]
I would like to see your solution since I am guessing it is totally different than mine

**Comment by calvinsettachatgul** [comment]
Can you upload your file with your solution too? @Hugosntss
